version: '3'
services:
  postgres-eligibility:
    image: postgres:13.3-alpine
    hostname: postgres
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=eligibility_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
    container_name: postgres_eligibility_service
    networks:
      - sales-order-service_localnet

  eligibility-service:
    image: natal/eligibility-service:1.0
    ports:
      - "8081:8081"
    container_name: eligibility_service
    depends_on:
      - postgres-eligibility
    networks:
      - sales-order-service_localnet

networks:
  sales-order-service_localnet:
    external: true